import sqlite3
import subprocess
import os
from flask import Flask, render_template_string, request, redirect, url_for

app = Flask(__name__)
DB_FILE = "local_library.db"
SQL_EXPORT = "schema.sql"
D1_DB_NAME = "my-library-db"

def init_db():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("""
    CREATE TABLE IF NOT EXISTS books (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        author TEXT NOT NULL,
        cover_url TEXT NOT NULL,
        b2_key TEXT NOT NULL
    );
    """)
    conn.commit()
    conn.close()

def export_to_sql():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM books")
    rows = cursor.fetchall()
    conn.close()

    with open(SQL_EXPORT, "w", encoding="utf-8") as f:
        f.write("-- Auto-generated by Local Python Dashboard\n")
        f.write("DROP TABLE IF EXISTS books;\n\n")
        f.write("CREATE TABLE books (\n")
        f.write("  id TEXT PRIMARY KEY,\n")
        f.write("  title TEXT NOT NULL,\n")
        f.write("  author TEXT NOT NULL,\n")
        f.write("  cover_url TEXT NOT NULL,\n")
        f.write("  b2_key TEXT NOT NULL\n")
        f.write(");\n\n")
        
        for row in rows:
            # Escape single quotes for SQL safety
            clean_title = row[1].replace("'", "''")
            clean_author = row[2].replace("'", "''")
            f.write(f"INSERT INTO books (id, title, author, cover_url, b2_key) VALUES ('{row[0]}', '{clean_title}', '{clean_author}', '{row[3]}', '{row[4]}');\n")

# Single HTML Template rendered directly from Python
HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Library Database Manager</title>
    <style>
        body { font-family: sans-serif; background: #0f172a; color: #f8fafc; padding: 2rem; margin: 0; }
        h1, h2 { color: #38bdf8; }
        .container { max-width: 1100px; margin: 0 auto; }
        .btn { background: #0284c7; color: white; border: none; padding: 10px 18px; border-radius: 6px; cursor: pointer; text-decoration: none; display: inline-block; font-weight: bold; }
        .btn:hover { background: #0369a1; }
        .btn-sync { background: #16a34a; font-size: 1.1rem; margin-bottom: 2rem; }
        .btn-sync:hover { background: #15803d; }
        .btn-danger { background: #dc2626; padding: 6px 12px; }
        .btn-danger:hover { background: #b91c1c; }
        
        form { background: #1e293b; padding: 1.5rem; border-radius: 8px; margin-bottom: 2rem; display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }
        form .full-width { grid-column: span 2; }
        input { background: #334155; border: 1px solid #475569; color: white; padding: 8px 12px; border-radius: 4px; width: 95%; }
        
        .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 1.5rem; }
        .card { background: #1e293b; border-radius: 8px; padding: 1rem; text-align: center; border: 1px solid #334155; }
        .card img { width: 100%; height: 220px; object-fit: cover; border-radius: 4px; }
        .card h3 { margin: 10px 0 5px 0; font-size: 1.1rem; }
        .card p { color: #94a3b8; font-size: 0.9rem; margin: 0 0 10px 0; }
        .badge { background: #334155; font-family: monospace; padding: 2px 6px; border-radius: 4px; font-size: 0.8rem; display: inline-block; margin-bottom: 10px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Local Library Dashboard</h1>
        
        <form action="/sync" method="POST" style="display:block; background:transparent; padding:0;">
            <button type="submit" class="btn btn-sync">☁️ Sync All Changes to Cloudflare D1</button>
        </form>

        <h2>Add or Update a Book</h2>
        <form action="/add" method="POST">
            <div>
                <label>Book ID (e.g., clean_code):</label><br>
                <input type="text" name="id" required placeholder="clean_code">
            </div>
            <div>
                <label>Title:</label><br>
                <input type="text" name="title" required placeholder="Clean Code">
            </div>
            <div>
                <label>Author:</label><br>
                <input type="text" name="author" required placeholder="Robert C. Martin">
            </div>
            <div>
                <label>B2 File Key (PDF filename without .pdf):</label><br>
                <input type="text" name="b2_key" required placeholder="clean_code">
            </div>
            <div class="full-width">
                <label>Cover Image URL:</label><br>
                <input type="url" name="cover_url" required placeholder="https://via.placeholder.com/150">
            </div>
            <div class="full-width">
                <button type="submit" class="btn">Save Book to Local Database</button>
            </div>
        </form>

        <h2>Current Catalog Visualizer ({{ books|length }} books)</h2>
        <div class="grid">
            {% for book in books %}
            <div class="card">
                <img src="{{ book[3] }}" alt="Cover">
                <h3>{{ book[1] }}</h3>
                <p>By {{ book[2] }}</p>
                <div class="badge">B2: {{ book[4] }}.pdf</div>
                <form action="/delete/{{ book[0] }}" method="POST" style="background:transparent; padding:0; display:block;">
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Delete this book?')">Delete</button>
                </form>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>
"""

@app.route("/")
def index():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM books")
    books = cursor.fetchall()
    conn.close()
    return render_template_string(HTML_TEMPLATE, books=books)

@app.route("/add", methods=["POST"])
def add_book():
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute(
        "INSERT OR REPLACE INTO books VALUES (?, ?, ?, ?, ?)",
        (request.form["id"], request.form["title"], request.form["author"], request.form["cover_url"], request.form["b2_key"])
    )
    conn.commit()
    conn.close()
    export_to_sql()
    return redirect(url_for("index"))

@app.route("/delete/<book_id>", methods=["POST"])
def delete_book(book_id):
    conn = sqlite3.connect(DB_FILE)
    cursor = conn.cursor()
    cursor.execute("DELETE FROM books WHERE id = ?", (book_id,))
    conn.commit()
    conn.close()
    export_to_sql()
    return redirect(url_for("index"))

@app.route("/sync", methods=["POST"])
def sync_cloudflare():
    export_to_sql()
    cmd = f"npx wrangler d1 execute {D1_DB_NAME} --remote --file=./{SQL_EXPORT}"
    subprocess.run(cmd, shell=True)
    return redirect(url_for("index"))

if __name__ == "__main__":
    init_db()
    export_to_sql()
    print("\n[+] Launching Local Library Dashboard at http://127.0.0.1:5000\n")
    app.run(port=5000)